USE [master]
GO

/****** Object:  Database [ProductionDB]    Script Date: 12.09.2022 15:53:59 ******/
CREATE DATABASE [ProductionDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductionDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL\MSSQL\DATA\ProductionDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductionDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL\MSSQL\DATA\ProductionDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductionDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProductionDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProductionDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProductionDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProductionDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProductionDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProductionDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProductionDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProductionDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProductionDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProductionDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProductionDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProductionDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProductionDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProductionDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProductionDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProductionDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProductionDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProductionDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProductionDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProductionDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProductionDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProductionDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProductionDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProductionDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProductionDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProductionDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProductionDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProductionDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProductionDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProductionDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ProductionDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProductionDB] SET  READ_WRITE 
GO

