ALTER SERVER ROLE [sysadmin] ADD MEMBER [OFFICE-MIKROSAM\leticijah];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

